config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :products

  resource :cart, only: [ :show] do
    post 'add', path: 'add/:id', on: :member
    post 'remove', path: 'remove/:id', on: :member
    get :checkout
  end

  resource :orders, only: [ :show, :index, :create ]

  root 'products#index'

end

app/views/shared/_cart.html.erb
<% if @cart %>
    <% if @cart.isCartEmpty? %>
        <p class="navbar-text navbar-right">
          Your cart is empty
        </p>
    <% else %>
        <p class="navbar-text navbar-right">
          <%= link_to "You have #{pluralize @cart.count, 'item'}", cart_path %>
        </p>
    <% end %>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Ecommerce Lite</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Products", products_path %></li>
        <li class="dropdown">
          <%= link_to '#', data: {toggle: "dropdown"} do %>
              Filter By Categories
              <span class="caret"></span>
          <% end %>
          <ul class="dropdown-menu">
            <% @categories.each do |category| %>
                <li>
                  <%= link_to category.name, category %>
                </li>
            <% end %>
          </ul>
        </li>
      </ul>
      <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-left">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Manage
                Products<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Add New Product', new_product_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Manage
                Categories<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Add New Category', new_category_path %></li>
                <li>
                  <%= link_to 'View All Category', categories_path %></li>
              </ul>
            </li>
          </ul>
      <% end %>

      <p class="navbar-text navbar-right">
        <% if user_signed_in? %>
            Logged in as <%= current_user.name %>
            <% if current_user && current_user.admin? %>
                <span class="bg-danger">(Admin)</span>
            <% end %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
            <%= link_to "Login", new_user_session_path, class: 'navbar-link' %>
        <% end %>
      </p>
      <%= render "shared/cart" %>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>