config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :products

  resource :cart, only: [ :show] do
    post 'add', path: 'add/:id', on: :member
    post 'remove', path: 'remove/:id', on: :member
    get :checkout
  end

  resource :orders, only: [ :show, :index, :create ]

  root 'products#index'

end

app/models/cart.rb
class Cart


  attr_reader :items
  attr_writer :items

  def self.build_from_hash hash
    items = if hash['cart'] then
              hash['cart']['items'].map do |item|
                CartItem.new item['product_id'], item['quantity']
              end
            else
              []
            end
    new items
  end

  def initialize(items = [])
    @items = items
  end

  def add_item(product_id)
    item = @items.find { |item| item.product_id == product_id }

    if item
      item.increment_cart_quantity
    else
      @items << CartItem.new(product_id)
    end

  end

  def isCartEmpty?
    @items.empty?
  end

  def count
    @items.length
  end

  def serialize
    items = @items.map { |item|
      {
          'product_id' => item.product_id,
          'quantity' => item.quantity
      }
    }

    {
        "items" => items
    }
  end

  def total_price
    @items.inject(0) { |sum, item| sum + item.total_price }
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :initialize_cart

  def add
    @cart.add_item params[:id]

    session["cart"] = @cart.serialize

    product = Product.find params[:id]
    redirect_to :back, notice: "Added #{product.name} to cart."
  end

  def show
  end

  def checkout
    @order_form = OrderForm.new user: User.new
  end

  def remove
    shopping_cart = Cart.build_from_hash(session)
    item_index_to_delete = shopping_cart.items.find_index { |item| item.product_id == params[:id] }

    @cart.items.delete_at(item_index_to_delete)
    session['cart'] = @cart.serialize

    redirect_to :back
  end

  def delete_value(value)
    delete_if { |k, v| v == value }
  end
end

app/views/carts/_summary.html.erb
<div class="col-md-14">
  <div class="table-responsive pull-right">
    <table class="table">
      <tbody>
      <% cart.items.each do |item| %>
          <tr>
            <td>
              <%= link_to (image_tag item.product.image.thumb, style: 'height:80px;width:80px;'), item.product, class: 'thumbnail pull-left' %>
            </td>
            <td>
              <%= link_to item.product.name, item.product %> x <%= label_tag item.quantity %>
              <br/>
              <%= number_to_currency item.price %>
            </td>
          </tr>
      <% end %>
      <tr>
        <td>
          <strong>Total :</strong>
        </td>
        <td>
          <%= number_to_currency cart.total_price %>
        </td>
      </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/carts/checkout.html.erb
<h1>Checkout</h1>

<% if @cart %>
    <% if @cart.isCartEmpty? %>
        <h4>Your cart is empty.</h4>
    <% else %>
        <%= render 'carts/summary', cart: @cart %>

        <%= form_for @order_form, url: orders_path do |f| %>
            <%= render 'orders/errors' %>
            <%= f.fields_for :user, f.object.user do |u| %>

                <div class="container">

                  <div class="row">
                    <div class="col-xs-7">
                      <form role="form">
                        <h2>Promotion !!
                          <small>Everything is free. Go ahead.</small>
                        </h2>
                        <hr class="colorgraph">

                        <div class="form-group">
                          <%= u.text_field :name, placeholder: 'Full Name', class: 'form-control input-lg' %>
                        </div>
                        <div class="form-group">
                          <%= u.text_field :email, placeholder: 'Email Address', class: 'form-control input-lg', type: 'email' %>
                        </div>
                        <div class="row">
                          <div class="col-xs-6 col-sm-6 col-md-6">
                            <div class="form-group">
                              <%= u.text_field :address, placeholder: 'Shipping Address', class: 'form-control input-lg' %>
                            </div>
                          </div>
                          <div class="col-xs-3 col-sm-3 col-md-3">
                            <div class="form-group">
                              <%= u.text_field :postal_code, placeholder: 'Zip Code', class: 'form-control input-lg' %>
                            </div>
                          </div>
                          <div class="col-xs-3 col-sm-3 col-md-3">
                            <div class="form-group">
                              <%= u.text_field :city, placeholder: 'City', class: 'form-control input-lg' %>
                            </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-xs-6 col-sm-6 col-md-6">
                            <div class="form-group">
                              <%= u.country_select :country, {priority_countries: ["US", "GB", "CA"]}, {class: 'form-control input-lg'} %>
                            </div>
                          </div>
                          <div class="col-xs-6 col-sm-6 col-md-6">
                            <div class="form-group">
                              <%= u.text_field :phone, placeholder: 'Phone', class: 'form-control input-lg' %>
                            </div>
                          </div>
                        </div>
                        <hr class="colorgraph">
                        <div class="row">
                          <div class="col-xs-6 col-md-6 pull-right">
                            <%= f.submit 'Place Order', :class => 'btn btn-primary btn-block btn-lg' %>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>

            <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/carts/show.html.erb
<style>

</style>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-10 col-md-offset-1">
      <table class="table table-hover">
        <thead>
        <tr>
          <th>Product</th>
          <th>Quantity</th>
          <th class="text-center">Price</th>
          <th class="text-center">Total</th>
          <th> </th>
        </tr>
        </thead>
        <tbody>
        <% @cart.items.each do |item| %>
            <tr>
              <td class="col-sm-8 col-md-6">
                <div class="media">

                    <%= link_to (image_tag item.product.image.thumb, style: 'height:80px;width:80px;'), item.product, class: 'thumbnail pull-left' %>

                  <div class="media-body">
                    <h4 class="media-heading">
                      <%= link_to item.product.name, item.product %>
                    </h4>
                  </div>
                </div></td>
              <td class="col-sm-1 col-md-1" style="text-align: center">
                <input type="text" class="form-control" id="exampleInputEmail1" value="<%= item.quantity %>">
              </td>
              <td class="col-sm-1 col-md-1 text-center"><strong>
                <%= number_to_currency item.price %>
              </strong></td>
              <td class="col-sm-1 col-md-1 text-center"><strong>
                <%= number_to_currency item.total_price %>
              </strong></td>
              <td class="col-sm-1 col-md-1">
                <%= link_to 'Remove', remove_cart_path(item.product.id), method: :post, data: {confirm: "Are you sure you wish to delete the product '#{item.product.name}' from your cart?"},
                            class: 'btn btn-danger btn-product' %>
              </td>
            </tr>
        <% end %>
        <tr>
          <td>   </td>
          <td>   </td>
          <td>   </td>
          <td><h3>Total</h3></td>
          <td class="text-right"><h3><strong>
            <%= number_to_currency @cart.total_price %>
          </strong></h3></td>
        </tr>
        <tr>
          <td>   </td>
          <td>   </td>
          <td>   </td>
          <td>
            <button type="button" class="btn btn-default">
              <span class="glyphicon glyphicon-shopping-cart"></span>
              <%= link_to "Continue Shopping", root_path %>
            </button></td>
          <td>
            <%= link_to "Checkout", checkout_cart_path, class: 'btn btn-primary' %>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div style="display: none">
  <h1>Shopping Cart</h1>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>
        Product Name
      </th>
      <th>
        Qty
      </th>
      <th class="text-right">
        Price
      </th>
    </tr>
    </thead>
    <tbody>
    <% @cart.items.each do |item| %>
        <tr>
          <td>
            <%= image_tag item.product.image.thumb %>
            <%= link_to item.product.name, item.product %></td>
          <td><%= item.quantity %></td>
          <td class="text-right"><%= number_to_currency item.total_price %></td>
        </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td class="text-right" colspan="3">
        <strong>
          Total : <%= number_to_currency @cart.total_price %>
        </strong>
      </td>
    </tr>
    </tfoot>
  </table>
</div>