config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :products

  resource :cart, only: [ :show] do
    post 'add', path: 'add/:id', on: :member
    post 'remove', path: 'remove/:id', on: :member
    get :checkout
  end

  resource :orders, only: [ :show, :index, :create ]

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  validates_presence_of :name, :price
  validates_numericality_of :price

  belongs_to :category
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :initialize_cart
  before_action :authenticate_admin!, only: [:new, :edit, :update, :destroy, :create]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :image, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <div class="well well-sm">
          <%= form_for(@product, multipart: true, :html => {:class => 'form-horizontal'}) do |f| %>
          <fieldset>
            <legend class="text-center"><%= locals[:zone]%></legend>

            <!-- Product Name input-->
            <div class="form-group">
              <label class="col-md-3 control-label" for="name"><%= f.label :name %></label>
              <div class="col-md-9">
                <%= f.text_field :name, class: 'form-control', placehoder: "Product Name" %>
              </div>
            </div>

            <!-- Price input-->
            <div class="form-group">
              <label class="col-md-3 control-label" for="price"><%= f.label :price %></label>
              <div class="col-md-9">
                <%= f.text_field :price, class: 'form-control', placehoder: "Price" %>
              </div>
            </div>

            <!-- Image file uploader -->
            <div class="form-group">
              <label class="col-md-3 control-label" for="message"><%= f.label :image %></label>
              <div class="col-md-9">
                <%= f.file_field :image, class: 'form-control', placehoder: "Price" %>
              </div>
            </div>

            <!-- Product categories -->
            <div class="form-group">
              <label class="col-md-3 control-label" for="message"><%= f.label :category %></label>
              <div class="col-md-9">
                <%= f.select :category_id, Category.all.map { |c| [c.name, c.id] } , {}, { class: 'form-control' }%>
              </div>
            </div>

            <!-- Form actions -->
            <div class="form-group">
              <div class="col-md-12 text-right">
                <%= f.submit 'Save Product', :class => 'btn btn-primary btn-lg' %>
              </div>
            </div>
          </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/_grid.html.erb
<div class="container">
  <div class="row-eq-height">
    <div class="col-md-11">
      <h3 style="padding-left: 15px"><%= category_name %></h3>

      <% if products.empty? && !user_signed_in? %>
          <h4>Welcome to Ecommerce Lite !! Currently there are no products on website.
            <br/><br/>Please <%= link_to "Click Here", new_user_session_path %> to sign up as Admin to add new products.
          </h4>
      <% end %>

      <% if products.empty? && user_signed_in? %>
          Welcome <%= current_user.name %>, To add new products click on <b>Manage Product => Add New Product</b> from top navigation.
      <% end %>

      <% products.each do |product| %>

          <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
              <%= image_tag product.image.thumb, :style => 'height:80px; width: 80px;' %>
              <div class="caption">
                <div class="row">
                  <div class="col-md-6 col-xs-6">
                    <h3><%= link_to product.name, product %></h3>
                  </div>
                  <div class="col-md-6 col-xs-6 price">
                    <h3>
                      <label><%= number_to_currency product.price %></label></h3>
                  </div>
                </div>
                <h4><label><%= product.category.name %></label></h4>
                <% if current_user && current_user.admin? %>
                    <div class="row">
                      <div class="col-md-6">
                        <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-primary btn-product' %>
                      </div>
                      <div class="col-md-6">
                        <%= link_to 'Delete', product, method: :delete, data: {confirm: 'Are you sure?'},
                                    class: 'btn btn-danger btn-product' %>
                      </div>
                    </div>
                <% else %>
                    <%= link_to 'Product Detail', product, class: 'btn btn-info btn-product' %>
                <% end %>
              </div>
            </div>
          </div>

      <% end %>
    </div>

  </div>
</div>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form', :locals => { :zone => 'Edit Product' } %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= render 'products/grid', products: @products, category_name: '' %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', :locals => { :zone => 'New Product' } %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container-fluid">
  <div class="content-wrapper">
    <div class="item-container">
      <div class="container">
        <%= link_to 'Back to product listing', products_path, class: 'btn btn-primary btn-xs active' %>
        <div class="col-md-12">
          <div class="product col-md-3 service-image-left">
            <%= image_tag @product.image, style: 'height:300px;' %>
          </div>
        </div>

        <div class="col-md-7">
          <div class="product-title"><%= @product.name %></div>
          <div class="product-info">Category :: <%= @product.category.name %></div>
          <div class="product-rating"><i class="fa fa-star gold"></i> <i class="fa fa-star gold"></i>
            <i class="fa fa-star gold"></i> <i class="fa fa-star gold"></i> <i class="fa fa-star-o"></i></div>
          <hr>
          <div class="product-price"><%= number_to_currency @product.price %>
            <div class="product-stock">In Stock</div>
          </div>


          <hr>
          <div class="btn-group cart">
            <%= link_to 'Add to cart', add_cart_path, method: :post, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div style="display: none">
  <h1>
    <%= @product.name %>
  </h1>

  <p>
    <%= number_to_currency @product.price %>
  </p>

  <p>
    <%= image_tag @product.image, style: 'height:300px;' %>
  </p>

  <p>
    <%= link_to 'Add to cart', add_cart_path, method: :post, class: 'btn btn-primary' %> |
    <%= link_to 'Edit', edit_product_path(@product) %> |
    <%= link_to 'Back', products_path %>
  </p>
</div>